/* GLDC member portal */
'use client';
import {useEffect,useState} from "react";
export default function Member(){
 const [u,setU]=useState<any>(null),[leads,setLeads]=useState<any[]>([]),[form,setForm]=useState({title:"",description:"",location:"",estimatedValue:""}),[pay,setPay]=useState({leadId:"",amount:"",phone:""}),[msg,setMsg]=useState("");
 const load=async()=>{const m=await fetch("/api/auth/me");const mj=await m.json();setU(mj.user);const l=await fetch("/api/leads");if(l.ok)setLeads(await l.json())};useEffect(()=>{load()},[]);
 const submit=async(e:any)=>{e.preventDefault();const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,estimatedValue:Number(form.estimatedValue)||0})});const j=await r.json();setMsg(j.error||"Project submitted for GLDC approval.");if(r.ok){setForm({title:"",description:"",location:"",estimatedValue:""});load()}};
 const payment=async()=>{const r=await fetch("/api/payments/mpesa/stk",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...pay,amount:Number(pay.amount)||0,description:"GLDC project deposit"})});const j=await r.json();setMsg(j.error||"M-PESA payment prompt sent. Complete it on your phone.");if(r.ok)load()};
 return <main className="shell"><header><img src="/gldc-logo.png"/><nav><a href="/">Website</a><a href="/login">Login</a></nav></header><section className="card"><span className="eyebrow">GLDC MEMBER PORTAL</span><h1>Projects, approvals & payments</h1>{u?<p className="muted">Signed in as <b>{u.firstName} {u.lastName}</b> · {u.status} · {u.memberType}</p>:<p>Loading account…</p>}{msg&&<div className="notice">{msg}</div>}</section><div className="grid"><section className="card"><h2>Submit a project / lead</h2><form onSubmit={submit}><label>Project title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea required rows={5} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Estimated value (KES)<input type="number" value={form.estimatedValue} onChange={e=>setForm({...form,estimatedValue:e.target.value})}/></label><button className="primary">Submit for approval</button></form></section><section className="card"><h2>Your project pipeline</h2>{leads.length?leads.map(l=><div key={l.id} style={{padding:"13px 0",borderBottom:"1px solid #edf0ed"}}><b>{l.title}</b><p className="muted">{l.location||"Location not supplied"} · KES {Number(l.estimatedValue||0).toLocaleString()}</p><span className="pill wait">{l.status}</span>{l.status==="approved"&&<div style={{marginTop:12}}><input placeholder="M-PESA phone 2547..." value={pay.leadId===l.id?pay.phone:""} onChange={e=>setPay({...pay,leadId:l.id,phone:e.target.value})}/><input style={{marginTop:7}} placeholder="Deposit amount" type="number" value={pay.leadId===l.id?pay.amount:""} onChange={e=>setPay({...pay,leadId:l.id,amount:e.target.value})}/><button style={{marginTop:8}} className="primary" onClick={payment}>Pay deposit via M-PESA</button></div>}</div>):<p className="muted">No project leads yet.</p>}</section></div></main>
}
