/* GLDC MANAGEMENT CONSOLE — production UI */
'use client';
import {useEffect,useState} from "react";
type Tab="overview"|"members"|"leads"|"payments"|"documents"|"operations";
const money=(n:any)=>`KES ${Number(n||0).toLocaleString("en-KE")}`;
const pretty=(s:any)=>String(s??"").replaceAll("_"," ");
export default function Admin(){
 const [tab,setTab]=useState<Tab>("overview"),[stats,setStats]=useState<any>(null),[users,setUsers]=useState<any[]>([]),[leads,setLeads]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[msg,setMsg]=useState(""),[busy,setBusy]=useState(false),[docFile,setDocFile]=useState<File|null>(null),[proof,setProof]=useState({project:"",member:"",amount:""});
 async function api(url:string,opts?:RequestInit){const r=await fetch(url,opts);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||"Request failed");return j}
 async function load(){try{const [s,u,l,p]=await Promise.all([api("/api/admin/overview"),api("/api/admin/users"),api("/api/admin/leads"),api("/api/admin/payments")]);setStats(s);setUsers(u);setLeads(l);setPayments(p)}catch(e:any){setMsg(e.message)}}
 useEffect(()=>{load()},[]);
 const action=async(fn:()=>Promise<any>,success:string)=>{setBusy(true);setMsg("");try{await fn();setMsg(success);await load()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}};
 const saveUser=()=>selected&&action(()=>api(`/api/admin/users/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(selected)}),"Member updated and backup attempted.");
 const approve=()=>selected&&action(()=>api(`/api/admin/users/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"approved",emailVerified:true})}),"Member approved.");
 const deleteUser=()=>selected&&confirm("Permanently delete this member?")&&action(()=>api(`/api/admin/users/${selected.id}`,{method:"DELETE"}),"Member deleted.");
 const leadStatus=(id:string,status:string)=>action(()=>api(`/api/admin/leads/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})}),`Lead ${status}.`);
 const backup=()=>action(()=>api("/api/admin/backup",{method:"POST"}),"MongoDB data backed up to the configured Google Sheet tabs.");
 async function upload(){if(!docFile)return;setBusy(true);try{const f=new FormData();f.append("file",docFile);await api("/api/documents/upload",{method:"POST",body:f});setMsg("Document stored in Google Drive and metadata backed up to Sheets.");setDocFile(null)}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function createPdf(){setBusy(true);try{const r=await fetch("/api/documents/project-proof",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...proof,amount:Number(proof.amount)||0})});if(!r.ok)throw new Error((await r.json()).error||"PDF failed");const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="GLDC-project-proof.pdf";a.click();URL.revokeObjectURL(url);setMsg("Signed-style project PDF generated, hashed, stored in Drive and registered for verification.")}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 const nav=[["overview","Overview","⌂"],["members","Members","◎"],["leads","Projects & Leads","⌁"],["payments","Payments","₵"],["documents","Documents & PDFs","▣"],["operations","Backup & Controls","⚙"]] as const;
 return <main className="console"><aside className="console-side"><div className="brand"><img src="/gldc-logo.png"/><div><b>GLDC</b><small>Management Console</small></div></div><div className="side-nav">{nav.map(([id,label,icon])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}><span>{icon}</span>{label}</button>)}</div><a className="side-home" href="/">← Public website</a></aside>
 <section className="console-body"><header className="console-top"><div><span className="eyebrow">GAVIN LAND & DESIGN CONSULTANTS</span><h1>{nav.find(x=>x[0]===tab)?.[1]}</h1></div><div className="top-actions"><span className="live"><i/> Production</span><button onClick={()=>load()}>Refresh</button></div></header>
 {msg&&<div className="notice">{msg}</div>}
 {tab==="overview"&&<><div className="metric-grid">{[["Total members",stats?.users,"users"],["Approved members",stats?.approved,"approved"],["Leads / projects",stats?.leads,"leads"],["Payments",stats?.payments,"payments"],["Documents",stats?.documents,"documents"],["Paid transactions",stats?.paid,"paid"]].map(x=><div className="metric" key={x[2]}><span>{x[0]}</span><strong>{x[1]??"—"}</strong><small>Live from MongoDB</small></div>)}</div><div className="split-panels"><section className="panel"><div className="panel-head"><h2>Recent audit activity</h2><button onClick={()=>setTab("operations")}>View controls</button></div>{stats?.audit?.length?<div className="activity">{stats.audit.map((a:any)=><div key={a.id}><b>{pretty(a.action)}</b><span>{a.entityId||a.actorId||"System"}</span><time>{a.createdAt?new Date(a.createdAt).toLocaleString():""}</time></div>)}</div>:<Empty text="No audit events yet."/>}</section><section className="panel"><h2>Production workflow</h2><div className="workflow"><b>1</b><span>Registration</span><i>→</i><b>2</b><span>Email verification</span><i>→</i><b>3</b><span>Admin approval</span><i>→</i><b>4</b><span>Payment</span></div><p className="muted">MongoDB is the system of record. Google Drive stores documents/PDFs and Google Sheets receives configured operational backups.</p></section></div></>}
 {tab==="members"&&<div className="split-panels members"><section className="panel"><div className="panel-head"><h2>Member registry</h2><span>{users.length} records</span></div><div className="tablewrap"><table><thead><tr><th>Name</th><th>Contact</th><th>Location</th><th>Role</th><th>Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.firstName} {u.lastName}</b><small>{u.memberType}</small></td><td>{u.email}<small>{u.phone}</small></td><td>{u.town}, {u.county}</td><td>{u.role}</td><td><span className={`pill ${u.status==="approved"?"ok":"wait"}`}>{pretty(u.status)}</span></td><td><button onClick={()=>setSelected({...u})}>Edit</button></td></tr>)}</tbody></table></div></section>{selected&&<section className="panel editor"><div className="panel-head"><h2>Edit member</h2><button onClick={()=>setSelected(null)}>×</button></div>{["firstName","lastName","email","phone","county","town","occupation","organization","memberType","role","status"].map(k=><label key={k}>{k}<input value={selected[k]??""} onChange={e=>setSelected({...selected,[k]:e.target.value})}/></label>)}<div className="form-actions"><button className="primary" disabled={busy} onClick={saveUser}>Save</button><button onClick={approve}>Approve</button><button className="danger" onClick={deleteUser}>Delete</button></div></section>}</div>}
 {tab==="leads"&&<section className="panel"><div className="panel-head"><h2>Lead & project pipeline</h2><span>Approval controls</span></div><div className="tablewrap"><table><thead><tr><th>Project</th><th>Location</th><th>Value</th><th>Status</th><th>Payment</th><th>Actions</th></tr></thead><tbody>{leads.map(l=><tr key={l.id}><td><b>{l.title}</b><small>{l.memberId}</small></td><td>{l.location||"—"}</td><td>{money(l.estimatedValue)}</td><td><span className="pill wait">{pretty(l.status)}</span></td><td>{pretty(l.paymentStatus)}</td><td><button onClick={()=>leadStatus(l.id,"approved")}>Approve</button><button onClick={()=>leadStatus(l.id,"processing")}>Process</button><button onClick={()=>leadStatus(l.id,"completed")}>Complete</button></td></tr>)}</tbody></table></div></section>}
 {tab==="payments"&&<section className="panel"><div className="panel-head"><h2>M-PESA transaction ledger</h2><span>Daraja callbacks update these records</span></div><div className="tablewrap"><table><thead><tr><th>Created</th><th>Amount</th><th>Phone</th><th>Status</th><th>Receipt</th><th>Checkout ID</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{p.createdAt?new Date(p.createdAt).toLocaleString():"—"}</td><td><b>{money(p.amount)}</b></td><td>{p.phone}</td><td><span className={`pill ${p.status==="paid"?"ok":"wait"}`}>{p.status}</span></td><td>{p.mpesaReceiptNumber||"—"}</td><td>{p.checkoutRequestId||"—"}</td></tr>)}</tbody></table></div></section>}
 {tab==="documents"&&<div className="split-panels"><section className="panel"><h2>Drive document intake</h2><p className="muted">Upload a document and GLDC stores the binary in the configured Google Drive folder while MongoDB stores ownership and metadata. The Vercel route accepts files below 4 MB.</p><input type="file" onChange={e=>setDocFile(e.target.files?.[0]||null)} accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx"/><button className="primary" disabled={!docFile||busy} onClick={upload}>Store in Drive</button></section><section className="panel"><h2>Generate project proof PDF</h2><div className="grid2"><label>Project<input value={proof.project} onChange={e=>setProof({...proof,project:e.target.value})}/></label><label>Member / Client<input value={proof.member} onChange={e=>setProof({...proof,member:e.target.value})}/></label><label>Amount (KES)<input type="number" value={proof.amount} onChange={e=>setProof({...proof,amount:e.target.value})}/></label></div><button className="primary" disabled={busy||!proof.project||!proof.member} onClick={createPdf}>Generate & archive PDF</button><p className="muted">Each PDF gets a unique GLDC document ID, SHA-256 hash, QR verification record and Drive copy.</p></section></div>}
 {tab==="operations"&&<div className="split-panels"><section className="panel"><h2>MongoDB → Google Sheets backup</h2><p>Run a full operational backup into the configured <b>Users, Leads, Payments, Documents and Audit</b> tabs. This is additive and preserves MongoDB as the primary database.</p><button className="primary" disabled={busy} onClick={backup}>Back up now</button></section><section className="panel"><h2>Production controls</h2><ul className="controls"><li><b>Database:</b> MongoDB Atlas</li><li><b>Documents:</b> Google Drive</li><li><b>Operational backup:</b> Google Sheets</li><li><b>Payments:</b> Safaricom Daraja / M-PESA</li><li><b>Email:</b> SMTP with verification workflow</li><li><b>PDF:</b> server generated + QR verification + hash</li><li><b>Security:</b> HTTP-only cookies, RBAC, audit logs, encrypted ID field</li></ul></section></div>}
 </section></main>
}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
