import Link from 'next/link';

export function Header(){return <header className="site-header"><div className="container nav-wrap"><Link href="/" className="brand"><img src="/gldc-logo.png" alt="GLDC"/></Link><nav><Link href="/services">Services</Link><Link href="/projects">Projects</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link><Link href="/login">Member Login</Link><Link className="nav-cta" href="/quote">Request a Quote</Link></nav></div></header>}
export function Footer(){return <footer><div className="container footer-grid"><div><img src="/gldc-logo.png" className="footer-logo" alt="GLDC"/><p>Professional land, design, development and project consultancy solutions.</p></div><div><h4>Explore</h4><Link href="/services">Services</Link><Link href="/projects">Projects</Link><Link href="/about">About GLDC</Link></div><div><h4>Start a project</h4><Link href="/quote">Request a quote</Link><Link href="/contact">Get a consultation</Link><Link href="/register">Become a member</Link></div></div><div className="container footer-bottom">© {new Date().getFullYear()} Gavin Land & Design Consultants. All rights reserved.</div></footer>}
export function Site({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
export const projects=[
 {title:'Residential Development',location:'Nairobi',type:'DESIGN',image:'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=1200&q=82',text:'Land planning, architectural design and development consultancy.'},
 {title:'Land Development Planning',location:'Kiambu',type:'LAND',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=82',text:'Site assessment and planning pathway for development.'},
 {title:'Commercial Design Advisory',location:'Kenya',type:'CONSULTANCY',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=82',text:'Concept design and project coordination consultancy.'}
];
